name: Build vault-client (No PyPi, just for testing)

on:
  push:  # Runs on any commit pushed to any branch
    branches:
      - '**'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Build packages
        run: |
          cd vault
          python3 -m pip install --upgrade build
          python3 -m build

      - name: Upload dist artifacts to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: vault-dist
          path: vault/dist/*
